name: Build & Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: mfe-kit/ci-templates/.github/workflows/release.yml@main
    with:
      repo_name: mfe-kit-dev-tools
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
